name: Changeo
favicon: null
layout_spectrum: 0.5191735320258886
typography_spectrum: 0.6642341949045658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21598502644337714
  lightness: 0.17413555178791285
  saturation: 0.6828336806502193
  rhythmicContrast: 0.4874232590664178
purpose: []
